### ISSUE TITLE
Mashing keys or typing really fast leads to inserted keys.

### ISSUE THREAD

**Issue by cyraid** [AdamMaras/vscode-overtype#16]
I've found this out by accident, but I've noticed every now and then while I was typing, my finger slipped and I hit two keys really fast. This resulted in one key being inserted? To test this, try just mashing the keyboard really fast while in overtype mode.

Reproducible?

**Comment by monkeyplays23** [comment]
I also have had problems with this I think this is because of key delay.  I think the way this program works is actually inserting then delete the next character since VSCode doesn't really have an overtype option (lame) so it is simulated by the above-mentioned action but if there is a delay in the algorithm the delete next character is slower than the key repeat so you could change the key delay to be slower to fix this maybe? This is not a great method because it causes a significant delay in typing as well. maybe need to grab the whole line and wait until the input stops for a certain amount of time then delete however many characters were entered by count rather than one character then delete the next character. It won't seem like "overtype" but it will definitely be faster.

**Comment by henrik-jensen** [comment]
Confirmation from me. Toggling overwrite, holding a key down, when auto-repeat delay times out, (usually OS-determined/global setting), the auto-repeated key starts to insert instead of overwriting.
System: Windows 10  ( `c:\>ver` -> Microsoft Windows [Version 10.0.18362.720])

**Comment by henrik-jensen** [comment]
Can't reproduce it with later versions of Vscode (later than 28 mar 2020 version, currently on ver 1.52.1), so it might have been magically fixed by an internal vscode change.
Sadly I haven't noticed the version when/if this supposedly "magical fix" (pure speculation from my side) should have occured, but can anybody confirm that it is fixed with vscode ver. 1.52.1 or later?

**Comment by mcpiroman** [comment]
@henrik-jensen Nope, it still persists on 1.53.0, on `Microsoft Windows [Version 10.0.18363.1377]`

**Comment by HactarCE** [comment]
The issue seems to be on [this line](https://github.com/AdamMaras/vscode-overtype/blob/cb4d5c6411ba08dbf537217a1a4a80c5166a25f2/src/behavior.ts#L14). Instead of `+ 1`, it should probably be `+ text.length`.
